import type { AppData,Assignment,Course,Section,Faculty,Room } from "./types";
import { teachingUnits } from "./rules";
export type Conflict={type:string;assignmentId:string;message:string};
const mins=(t:string)=>{const[h,m]=t.split(":").map(Number);return h*60+m};
const overlap=(a:Assignment,b:Assignment)=>a.day===b.day&&mins(a.start)<mins(b.end)&&mins(b.start)<mins(a.end);
const inside=(day:string,start:string,end:string,periods:{day:string;start:string;end:string}[])=>periods.some(p=>p.day===day&&mins(start)>=mins(p.start)&&mins(end)<=mins(p.end));
export function conflictsFor(a:Assignment,all:Assignment[],data:Pick<AppData,"faculty"|"courses"|"sections"|"rooms">):Conflict[]{
 const out:Conflict[]=[];const course=data.courses.find(x=>x.code===a.courseCode),section=data.sections.find(x=>x.id===a.sectionId),faculty=data.faculty.find(x=>x.id===a.facultyId),room=data.rooms.find(x=>x.id===a.roomId);
 if(!course||!section||!faculty||!room)return[{type:"reference",assignmentId:a.id,message:`${a.id} has an unknown reference.`}];
 for(const b of all)if(b.id!==a.id&&overlap(a,b)){const bc=data.courses.find(x=>x.code===b.courseCode);if(b.roomId===a.roomId)out.push({type:"room",assignmentId:a.id,message:`Room ${room.id} is already assigned to ${bc?.code}, ${b.sectionId}, on ${a.day} from ${b.start} to ${b.end}.`});if(b.facultyId===a.facultyId)out.push({type:"faculty",assignmentId:a.id,message:`${faculty.nameEn} is already teaching ${bc?.code} on ${a.day} from ${b.start} to ${b.end}.`});const bs=data.sections.find(x=>x.id===b.sectionId);if(b.sectionId===a.sectionId||section.sharedGroups.some(g=>bs?.sharedGroups.includes(g)))out.push({type:"students",assignmentId:a.id,message:`${section.id} or its shared student group overlaps ${b.sectionId} on ${a.day}.`})}
 if(room.capacity<section.students)out.push({type:"capacity",assignmentId:a.id,message:`Room ${room.id} capacity (${room.capacity}) is below ${section.id} enrollment (${section.students}).`});
 if(room.type!==course.roomType)out.push({type:"room-type",assignmentId:a.id,message:`${course.code} requires ${course.roomType}; ${room.id} is ${room.type}.`});
 if(room.campus!==section.campus||faculty.campus!==section.campus)out.push({type:"campus",assignmentId:a.id,message:`Campus/section mismatch for ${course.code}, ${section.id}.`});
 if(faculty.specialization!==course.specialization&&!a.overrideReason)out.push({type:"specialization",assignmentId:a.id,message:`${faculty.nameEn} specialization does not match ${course.code}; an authorized override reason is required.`});
 if(!inside(a.day,a.start,a.end,faculty.available)||inside(a.day,a.start,a.end,faculty.unavailable))out.push({type:"faculty-availability",assignmentId:a.id,message:`${faculty.nameEn} is unavailable on ${a.day} from ${a.start} to ${a.end}.`});
 if(!inside(a.day,a.start,a.end,room.availability))out.push({type:"room-availability",assignmentId:a.id,message:`Room ${room.id} is unavailable on ${a.day} from ${a.start} to ${a.end}.`});return out;
}
export function allConflicts(data:AppData){return data.assignments.flatMap(a=>conflictsFor(a,data.assignments,data))}
type Need={course:Course;section:Section;faculty:Faculty};
export function generate(data:AppData,mode:"balanced"|"faculty"|"compact"="balanced"){
 const started=Date.now(),locked=[...data.assignments.filter(a=>a.locked)],existing=new Set(locked.map(a=>`${a.courseCode}|${a.sectionId}`));const needs:Need[]=[];
 for(const s of data.sections)for(const code of s.courseCodes){const c=data.courses.find(x=>x.code===code);if(!c||existing.has(`${code}|${s.id}`))continue;const f=data.faculty.find(x=>x.specialization===c.specialization&&x.campus===s.campus);if(f)for(let i=0;i<c.meetingsPerWeek;i++)needs.push({course:c,section:s,faculty:f})}
 needs.sort((a,b)=>candidateCount(a,data)-candidateCount(b,data)||a.course.code.localeCompare(b.course.code));let result:Assignment[]|null=null;
 const search=(i:number,current:Assignment[]):boolean=>{if(Date.now()-started>data.settings.timeoutMs)return false;if(i===needs.length){result=current;return true}const n=needs[i];for(const c of candidates(n,data,mode)){const a:Assignment={...c,id:`GEN-${String(i+1).padStart(3,"0")}`,createdAt:new Date(0).toISOString(),updatedAt:new Date().toISOString(),locked:false,overtime:false,approval:"not-required",teachingUnits:teachingUnits(n.course)};if(conflictsFor(a,current,data).length===0&&search(i+1,[...current,a]))return true}return false};search(0,locked);
 if(!result)return{ok:false as const,assignments:locked,score:0,warnings:["No valid schedule found within the configured timeout."]};const cs=(result as Assignment[]).flatMap(a=>conflictsFor(a,result as Assignment[],data));return{ok:true as const,assignments:result as Assignment[],score:Math.max(0,100-cs.length*8),warnings:cs.map(c=>c.message)};
}
function candidateCount(n:Need,d:AppData){return candidates(n,d,"balanced").length}
function candidates(n:Need,d:AppData,mode:string){const arr:Omit<Assignment,"id"|"createdAt"|"updatedAt"|"teachingUnits"|"locked"|"overtime"|"approval">[]=[];for(const day of d.settings.days)for(let h=d.settings.startHour;h<=d.settings.endHour-Math.ceil(n.course.duration/60);h++)for(const room of d.rooms.filter(r=>r.campus===n.section.campus&&r.type===n.course.roomType&&r.capacity>=n.section.students)){const start=`${String(h).padStart(2,"0")}:00`,endMin=h*60+n.course.duration,end=`${String(Math.floor(endMin/60)).padStart(2,"0")}:${String(endMin%60).padStart(2,"0")}`;arr.push({courseCode:n.course.code,sectionId:n.section.id,facultyId:n.faculty.id,roomId:room.id,day,start,end})}return arr.sort((a,b)=>{const ap=n.faculty.preferredDays.includes(a.day)?0:1,bp=n.faculty.preferredDays.includes(b.day)?0:1;return mode==="faculty"?ap-bp||a.start.localeCompare(b.start):mode==="compact"?a.start.localeCompare(b.start)||a.day.localeCompare(b.day):a.day.localeCompare(b.day)||a.start.localeCompare(b.start)||a.roomId.localeCompare(b.roomId)})}
